SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS statuses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  position INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  status_id INT NOT NULL DEFAULT 1,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_tags (
  task_id INT NOT NULL,
  tag_id INT NOT NULL,
  PRIMARY KEY (task_id, tag_id),
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  admin_id INT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Статусы по умолчанию
INSERT INTO statuses (id, name, position)
  SELECT 1, 'ToDo', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM statuses WHERE id = 1);
INSERT INTO statuses (name, position)
  SELECT 'In Progress', 2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM statuses WHERE name = 'In Progress');
INSERT INTO statuses (name, position)
  SELECT 'Ready For Review', 3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM statuses WHERE name = 'Ready For Review');
INSERT INTO statuses (name, position)
  SELECT 'Done', 4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM statuses WHERE name = 'Done');
-- Теги по умолчанию
INSERT INTO tags (name)
  SELECT 'tech issue' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tags WHERE name = 'tech issue');
INSERT INTO tags (name)
  SELECT 'tech question' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tags WHERE name = 'tech question');
INSERT INTO tags (name)
  SELECT 'fatal error' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tags WHERE name = 'fatal error');
INSERT INTO tags (name)
  SELECT 'sales question' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tags WHERE name = 'sales question');